### ISSUE TITLE
路径

### ISSUE THREAD

**Issue by lkyqyy** [FlyingMoon-GitHub/ACNet#2]
dataset.py  第25行
with open(os.path.join(self.root_path,self.dataset, self.anno_dir, self.anno_file), 'r') as f:
  我尝试将（os.path.join(self.root_path,self.dataset, self.anno_dir, self.anno_file）替换成为（‘data/CUB-200-2011/annos/annos_train.txt’）这个地方就可以正常读取，但是采用os.path.join(self.root_path,self.dataset, self.anno_dir, self.anno_file所对应的路径，就是找不到文件FileNotFoundError: [Errno 2] No such file or directory: '.\\data\\CUB-200-2011\\annos\\annos_train.txt'，我按照您之前说的进行了修改，还是一样的问题出现。

**Comment by xymyys** [comment]
我也遇到了同样的问题，请问最后是怎么解决的呢？
